build inly linux
Signed-off-by: dwertent <david.wertenteil@kaleido.io>

diff --git a/.github/workflows/paladin-PR-build.yml b/.github/workflows/paladin-PR-build.yml
--- a/.github/workflows/paladin-PR-build.yml
+++ b/.github/workflows/paladin-PR-build.yml
@@ -8,11 +8,7 @@ on:
 
 jobs:
   build:
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os: [ubuntu-latest, macos-latest, windows-latest]
-
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
         with:
@@ -21,19 +17,10 @@ jobs:
 
       # Install protoc only on non-Windows systems
       - name: Install protoc (Linux/MacOS)
-        if: runner.os != 'Windows'
         run: |
           PB_REL="https://github.com/protocolbuffers/protobuf/releases"
-          curl -LO $PB_REL/download/v25.1/protoc-25.1-${{ runner.os == 'Linux' && 'linux' || 'osx' }}-x86_64.zip
-          unzip protoc-25.1-${{ runner.os == 'Linux' && 'linux' || 'osx' }}-x86_64.zip -d protoc
-          echo "${PWD}/protoc/bin" >> $GITHUB_PATH
-
-      # Skip protoc installation for Windows
-      - name: Install protoc (Windows)
-        if: runner.os == 'Windows'
-        run: |
-          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v25.1/protoc-25.1-win64.zip
-          unzip protoc-25.1-win64.zip -d protoc
+          curl -LO $PB_REL/download/v25.1/protoc-25.1-linux-x86_64.zip
+          unzip protoc-25.1-linux-x86_64.zip -d protoc
           echo "${PWD}/protoc/bin" >> $GITHUB_PATH
 
       # Set up Java
@@ -67,9 +54,9 @@ jobs:
       # Verify the files in build/libs for all OS types
       - name: Check files in build/libs
         run: |
-          test -f build/libs/${{ runner.os == 'Windows' && 'libstarter.dll' || (runner.os == 'macOS' && 'libstarter.dylib' || 'libstarter.so') }} || (echo "libstarter library not found" && exit 1)
+          test -f build/libs/libstarter.so || (echo "libstarter library not found" && exit 1)
           test -f build/libs/libstarter.h || (echo "libstarter.h not found" && exit 1)
-          test -f build/libs/${{ runner.os == 'Windows' && 'libcore.dll' || (runner.os == 'macOS' && 'libcore.dylib' || 'libcore.so') }} || (echo "libcore library not found" && exit 1)
+          test -f build/libs/libcore.so || (echo "libcore library not found" && exit 1)
           test -f build/libs/libcore.h || (echo "libcore.h not found" && exit 1)
           test -f build/libs/paladin.jar || (echo "paladin.jar not found" && exit 1)
 
